### ISSUE TITLE
Serialization error returned if wallet has no tokens

### ISSUE THREAD

**Issue by acroquelois** [CenturioHackMoney21/centurio-back#13]
J'ai un retour bizarre sur l'url avec le wallet:
![image](https://user-images.githubusercontent.com/49721708/122999088-1bda6580-d3ae-11eb-8e4e-3c81d4f7fa7b.png)
J'ai oublié qlq chose ?

**Comment by octogene** [comment]
Tu n'as aucun Token. Je n'avais pas prévu que quelqu'un utiliserait l'API sans adresse avec tokens.
